version: "3"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "4000:4000"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: postgres
